# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CaramelUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 471)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Bg = QtWidgets.QLabel(self.centralwidget)
        self.Bg.setGeometry(QtCore.QRect(-10, -10, 851, 501))
        self.Bg.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.Bg.setText("")
        self.Bg.setObjectName("Bg")
        self.bg_border = QtWidgets.QLabel(self.centralwidget)
        self.bg_border.setGeometry(QtCore.QRect(0, 0, 831, 471))
        self.bg_border.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 0, 0);\n"
"border: 2px solid  rgb(255, 255, 255);")
        self.bg_border.setText("")
        self.bg_border.setObjectName("bg_border")
        self.Gif = QtWidgets.QLabel(self.centralwidget)
        self.Gif.setGeometry(QtCore.QRect(200, 10, 411, 321))
        self.Gif.setStyleSheet("z-index: 1;")
        self.Gif.setText("")
        self.Gif.setPixmap(QtGui.QPixmap("../../Downloads/Siri_1.gif"))
        self.Gif.setScaledContents(True)
        self.Gif.setObjectName("Gif")
        self.Terminal = QtWidgets.QLabel(self.centralwidget)
        self.Terminal.setGeometry(QtCore.QRect(20, 280, 791, 181))
        self.Terminal.setStyleSheet("background-color: black;\n"
"border: 2px solid white;\n"
"border-radius: 15px;\n"
"z-index: 2;")
        self.Terminal.setText("")
        self.Terminal.setObjectName("Terminal")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
